// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using TF47_API.Database;

namespace TF47_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210315145134_added_issues_and_reorganisation")]
    partial class added_issues_and_reorganisation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum(null, "side", new[] { "civilian", "bluefor", "redfor", "independent" })
                .HasPostgresEnum(null, "vehicle_type", new[] { "infantry", "light_vehicle", "tank", "helicopter", "fixed_wing", "boat" })
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<long>("GroupsGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groups_group_id");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_user_id");

                    b.HasKey("GroupsGroupId", "UsersUserId")
                        .HasName("pk_service_usergroups");

                    b.HasIndex("UsersUserId")
                        .HasDatabaseName("ix_service_usergroups_users_user_id");

                    b.ToTable("service_usergroups");
                });

            modelBuilder.Entity("PlayerWhitelist", b =>
                {
                    b.Property<long>("PlayerWhitelistingsWhitelistId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_whitelistings_whitelist_id");

                    b.Property<long>("PlayersPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("players_player_id");

                    b.HasKey("PlayerWhitelistingsWhitelistId", "PlayersPlayerId")
                        .HasName("pk_gameserver_playerwhitelistings");

                    b.HasIndex("PlayersPlayerId")
                        .HasDatabaseName("ix_gameserver_playerwhitelistings_players_player_id");

                    b.ToTable("gameserver_playerwhitelistings");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_created");

                    b.HasKey("CampaignId")
                        .HasName("pk_gameserver_campaigns");

                    b.ToTable("gameserver_campaigns");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Chat", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("text");

                    b.Property<DateTime>("TimeSend")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_send");

                    b.HasKey("ChatId")
                        .HasName("pk_gameserver_chats");

                    b.HasIndex("Channel")
                        .HasDatabaseName("ix_gameserver_chats_channel");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_gameserver_chats_player_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_gameserver_chats_session_id");

                    b.ToTable("gameserver_chats");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Kill", b =>
                {
                    b.Property<long>("KillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("kill_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Distance")
                        .HasColumnType("bigint")
                        .HasColumnName("distance");

                    b.Property<long>("GameTime")
                        .HasColumnType("bigint")
                        .HasColumnName("game_time");

                    b.Property<long?>("KillerPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("killer_player_id");

                    b.Property<int>("KillerSide")
                        .HasColumnType("integer")
                        .HasColumnName("killer_side");

                    b.Property<int>("KillerVehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("killer_vehicle_type");

                    b.Property<DateTime>("RealTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("real_time");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("VehicleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_name");

                    b.Property<long?>("VictimPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("victim_player_id");

                    b.Property<int>("VictimSide")
                        .HasColumnType("integer")
                        .HasColumnName("victim_side");

                    b.Property<int>("VictimVehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("victim_vehicle_type");

                    b.Property<string>("Weapon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("weapon");

                    b.HasKey("KillId")
                        .HasName("pk_gameserver_kills");

                    b.HasIndex("KillerPlayerId")
                        .HasDatabaseName("ix_gameserver_kills_killer_player_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_gameserver_kills_session_id");

                    b.HasIndex("VictimPlayerId")
                        .HasDatabaseName("ix_gameserver_kills_victim_player_id");

                    b.ToTable("gameserver_kills");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Mission", b =>
                {
                    b.Property<long>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mission_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("MissionType")
                        .HasColumnType("integer")
                        .HasColumnName("mission_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("MissionId")
                        .HasName("pk_gameserver_missions");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_gameserver_missions_campaign_id");

                    b.ToTable("gameserver_missions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Playtime", b =>
                {
                    b.Property<long>("PlayTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("play_time_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<TimeSpan>("TimePlayedBoat")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_boat");

                    b.Property<TimeSpan>("TimePlayedFixedWing")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_fixed_wing");

                    b.Property<TimeSpan>("TimePlayedHelicopter")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_helicopter");

                    b.Property<TimeSpan>("TimePlayedInfantry")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_infantry");

                    b.Property<TimeSpan>("TimePlayedTank")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_tank");

                    b.Property<TimeSpan>("TimePlayedVehicle")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_vehicle");

                    b.Property<TimeSpan>("TimeTrackedObjective")
                        .HasColumnType("interval")
                        .HasColumnName("time_tracked_objective");

                    b.HasKey("PlayTimeId")
                        .HasName("pk_gameserver_playtimes");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_gameserver_playtimes_player_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_gameserver_playtimes_session_id");

                    b.ToTable("gameserver_playtimes");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Position", b =>
                {
                    b.Property<long>("PositionTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position_tracker_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Direction")
                        .HasColumnType("bigint")
                        .HasColumnName("direction");

                    b.Property<string>("Group")
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<bool>("IsAwake")
                        .HasColumnType("boolean")
                        .HasColumnName("is_awake");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("boolean")
                        .HasColumnName("is_driver");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<NpgsqlPoint>("Pos")
                        .HasColumnType("point")
                        .HasColumnName("pos");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<string>("VehicleName")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_name");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.Property<long>("Velocity")
                        .HasColumnType("bigint")
                        .HasColumnName("velocity");

                    b.HasKey("PositionTrackerId")
                        .HasName("pk_gameserver_playerpositions");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_gameserver_playerpositions_player_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_gameserver_playerpositions_session_id");

                    b.ToTable("gameserver_playerpositions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("mission_id");

                    b.Property<int>("MissionType")
                        .HasColumnType("integer")
                        .HasColumnName("mission_type");

                    b.Property<DateTime>("SessionCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("session_created");

                    b.Property<DateTime?>("SessionEnded")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("session_ended");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("world_name");

                    b.HasKey("SessionId")
                        .HasName("pk_gameserver_sessions");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_gameserver_sessions_mission_id");

                    b.ToTable("gameserver_sessions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Whitelist", b =>
                {
                    b.Property<long>("WhitelistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("whitelist_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("WhitelistId")
                        .HasName("pk_gameserver_whitelists");

                    b.ToTable("gameserver_whitelists");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("player_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("FirstVisit")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_visit");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_visit");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player_name");

                    b.Property<string>("PlayerUid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player_uid");

                    b.HasKey("PlayerId")
                        .HasName("pk_gameserver_players");

                    b.ToTable("gameserver_players");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("group_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("background_color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("text_color");

                    b.HasKey("GroupId")
                        .HasName("pk_service_groups");

                    b.ToTable("service_groups");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.GroupPermission", b =>
                {
                    b.Property<long>("GroupPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("group_permission_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CanBanPermanent")
                        .HasColumnType("boolean")
                        .HasColumnName("can_ban_permanent");

                    b.Property<bool>("CanBanUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_ban_users");

                    b.Property<bool>("CanCreateServers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_servers");

                    b.Property<bool>("CanDeleteUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete_users");

                    b.Property<bool>("CanEditGroups")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_groups");

                    b.Property<bool>("CanEditServers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_servers");

                    b.Property<bool>("CanEditUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_users");

                    b.Property<bool>("CanUseServers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_servers");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.HasKey("GroupPermissionId")
                        .HasName("pk_service_grouppermissions");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_grouppermissions_group_id");

                    b.ToTable("service_grouppermissions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.Issue", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<Guid?>("IssueCreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_creator_user_id");

                    b.Property<long>("IssueGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_group_id");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_created");

                    b.Property<DateTime>("TimeLastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_last_updated");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("IssueId")
                        .HasName("pk_service_issues");

                    b.HasIndex("IssueCreatorUserId")
                        .HasDatabaseName("ix_service_issues_issue_creator_user_id");

                    b.HasIndex("IssueGroupId")
                        .HasDatabaseName("ix_service_issues_issue_group_id");

                    b.ToTable("service_issues");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.IssueGroup", b =>
                {
                    b.Property<long>("IssueGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("issue_group_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("GroupDescription")
                        .HasColumnType("text")
                        .HasColumnName("group_description");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<DateTime>("TimeGroupCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_group_created");

                    b.HasKey("IssueGroupId")
                        .HasName("pk_service_issuegroups");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("ix_service_issuegroups_group_name");

                    b.ToTable("service_issuegroups");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.IssueItem", b =>
                {
                    b.Property<long>("IssueItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("issue_item_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_created");

                    b.Property<DateTime?>("TimeLastEdited")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_last_edited");

                    b.HasKey("IssueItemId")
                        .HasName("pk_service_issueitems");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_service_issueitems_author_user_id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_service_issueitems_issue_id");

                    b.ToTable("service_issueitems");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean")
                        .HasColumnName("banned");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("FirstTimeSeen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_time_seen");

                    b.Property<DateTime>("LastTimeSeen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_time_seen");

                    b.Property<string>("Mail")
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_url");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steam_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_service_users");

                    b.HasIndex("SteamId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_users_steam_id");

                    b.ToTable("service_users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Services.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .HasConstraintName("fk_service_usergroups_groups_groups_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TF47_API.Database.Models.Services.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .HasConstraintName("fk_service_usergroups_users_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerWhitelist", b =>
                {
                    b.HasOne("TF47_API.Database.Models.GameServer.Whitelist", null)
                        .WithMany()
                        .HasForeignKey("PlayerWhitelistingsWhitelistId")
                        .HasConstraintName("fk_gameserver_playerwhitelistings_whitelist_player_whitelistin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TF47_API.Database.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersPlayerId")
                        .HasConstraintName("fk_gameserver_playerwhitelistings_players_players_player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Chat", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Player", "Player")
                        .WithMany("PlayerChats")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_gameserver_chats_gameserver_players_player_id");

                    b.HasOne("TF47_API.Database.Models.GameServer.Session", "Session")
                        .WithMany("Chats")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_gameserver_chats_gameserver_sessions_session_id");

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Kill", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Player", "Killer")
                        .WithMany("PlayerKills")
                        .HasForeignKey("KillerPlayerId")
                        .HasConstraintName("fk_gameserver_kills_gameserver_players_killer_player_id");

                    b.HasOne("TF47_API.Database.Models.GameServer.Session", "Session")
                        .WithMany("Kills")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_gameserver_kills_gameserver_sessions_session_id");

                    b.HasOne("TF47_API.Database.Models.Player", "Victim")
                        .WithMany("PlayerDeaths")
                        .HasForeignKey("VictimPlayerId")
                        .HasConstraintName("fk_gameserver_kills_gameserver_players_victim_player_id");

                    b.Navigation("Killer");

                    b.Navigation("Session");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Mission", b =>
                {
                    b.HasOne("TF47_API.Database.Models.GameServer.Campaign", "Campaign")
                        .WithMany("Missions")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_gameserver_missions_gameserver_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Playtime", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Player", "Player")
                        .WithOne("PlayerPlaytime")
                        .HasForeignKey("TF47_API.Database.Models.GameServer.Playtime", "PlayerId")
                        .HasConstraintName("fk_gameserver_playtimes_gameserver_players_player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TF47_API.Database.Models.GameServer.Session", "Session")
                        .WithMany("PlayTimes")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_gameserver_playtimes_gameserver_sessions_session_id");

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Position", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Player", "Player")
                        .WithMany("PlayerPositions")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_gameserver_playerpositions_gameserver_players_player_id");

                    b.HasOne("TF47_API.Database.Models.GameServer.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_gameserver_playerpositions_gameserver_sessions_session_id");

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Session", b =>
                {
                    b.HasOne("TF47_API.Database.Models.GameServer.Mission", "Mission")
                        .WithMany("Sessions")
                        .HasForeignKey("MissionId")
                        .HasConstraintName("fk_gameserver_sessions_missions_mission_id");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.GroupPermission", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Services.Group", "Group")
                        .WithOne("GroupPermission")
                        .HasForeignKey("TF47_API.Database.Models.Services.GroupPermission", "GroupId")
                        .HasConstraintName("fk_service_grouppermissions_service_groups_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.Issue", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Services.User", "IssueCreator")
                        .WithMany()
                        .HasForeignKey("IssueCreatorUserId")
                        .HasConstraintName("fk_service_issues_service_users_issue_creator_user_id");

                    b.HasOne("TF47_API.Database.Models.Services.IssueGroup", "IssueGroup")
                        .WithMany("Issues")
                        .HasForeignKey("IssueGroupId")
                        .HasConstraintName("fk_service_issues_service_issuegroups_issue_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueCreator");

                    b.Navigation("IssueGroup");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.IssueItem", b =>
                {
                    b.HasOne("TF47_API.Database.Models.Services.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("fk_service_issueitems_service_users_author_user_id");

                    b.HasOne("TF47_API.Database.Models.Services.Issue", "Issue")
                        .WithMany("IssueItems")
                        .HasForeignKey("IssueId")
                        .HasConstraintName("fk_service_issueitems_service_issues_issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Campaign", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Mission", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.GameServer.Session", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kills");

                    b.Navigation("PlayTimes");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Player", b =>
                {
                    b.Navigation("PlayerChats");

                    b.Navigation("PlayerDeaths");

                    b.Navigation("PlayerKills");

                    b.Navigation("PlayerPlaytime");

                    b.Navigation("PlayerPositions");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.Group", b =>
                {
                    b.Navigation("GroupPermission");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.Issue", b =>
                {
                    b.Navigation("IssueItems");
                });

            modelBuilder.Entity("TF47_API.Database.Models.Services.IssueGroup", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
